config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  get 'home/start'

  root to: 'home#index'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
  
  def start
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_circle.html.erb
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<svg width="150px" height="150px" viewBox="0 0 73 74" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:sketch="http://www.bohemiancoding.com/sketch/ns" id="circle-graphic">
    <title>Slice 1</title>
    <description>Created with Sketch (http://www.bohemiancoding.com/sketch)</description>
    <defs></defs>
    <g id="Page-1" stroke="none" stroke-width="1" fill="none" fill-rule="evenodd" sketch:type="MSPage">
        <path d="M1.05761719,32.8955078 C1.05761719,32.8955069 6.37597656,33.0810547 6.37597656,33.0810547 C6.37597656,33.0810547 7.21090386,23.6845117 14.2637141,16.5007251 C14.9970337,15.7537871 15.7975743,15.030771 16.6713867,14.3447266 C25.9492188,7.06054687 32.0996094,7.06054687 32.0996094,7.06054687 L32.0996094,1.87109375 C32.0996094,1.87109375 23.0478516,1.85351562 12.7988281,10.5898437 C2.54980449,19.3261716 1.05761719,32.8955088 1.05761719,32.8955078 Z M40.796875,1.48242188 C40.796876,1.48242188 40.6113281,6.80078125 40.6113281,6.80078125 C40.6113281,6.80078125 50.0078711,7.63570855 57.1916578,14.6885188 C57.9385958,15.4218384 58.6616118,16.222379 59.3476562,17.0961914 C66.6318359,26.3740234 66.6318359,32.5244141 66.6318359,32.5244141 L71.8212891,32.5244141 C71.8212891,32.5244141 71.8388672,23.4726562 63.1025391,13.2236328 C54.3662112,2.97460918 40.796874,1.48242187 40.796875,1.48242188 Z M72.2099609,41.2216797 C72.2099609,41.2216806 66.8916016,41.0361328 66.8916016,41.0361328 C66.8916016,41.0361328 66.0566743,50.4326758 59.003864,57.6164624 C58.2705444,58.3634004 57.4700038,59.0864165 56.5961914,59.7724609 C47.3183594,67.0566406 41.1679688,67.0566406 41.1679688,67.0566406 L41.1679688,72.2460938 C41.1679688,72.2460938 50.2197266,72.2636719 60.46875,63.5273438 C70.7177736,54.7910159 72.2099609,41.2216787 72.2099609,41.2216797 Z M32.4707031,72.6347656 C32.4707022,72.6347656 32.65625,67.3164062 32.65625,67.3164062 C32.65625,67.3164062 23.259707,66.481479 16.0759204,59.4286687 C15.3289824,58.6953491 14.6059664,57.8948085 13.9199219,57.0209961 C6.63574219,47.7431641 6.63574219,41.5927734 6.63574219,41.5927734 L1.44628906,41.5927734 C1.44628906,41.5927734 1.42871094,50.6445312 10.1650391,60.8935547 C18.901367,71.1425783 32.4707041,72.6347656 32.4707031,72.6347656 Z" id="Path-1" stroke="#979797" fill="#7ED321" sketch:type="MSShapeGroup"></path>
    </g>
</svg>

app/views/home/index.html.erb
<h1>Point of Attraction</h1>
<p>It only takes 68 seconds</p>

<%# link_to "Start", home_start_path, id: "start-button"%>
<%= link_to "Start", "#", id: "start-button", remote: true %>
<%= link_to "Stop", "#", id: "stop-button", remote: true %>
<%= link_to "Reset", "#", id: "reset-button", remote: true %>

<br>
<br>
<div id="main-timer-container">
  <%# render 'circle' %>
  <span id="timer">0</span>
</div>
<div id="timers-container">
  <div id="timer-1">0</div>
  <div id="timer-2"> </div>
  <div id="timer-3"> </div>
  <div id="timer-4"> </div>
</div>

<audio id="bell-tone" class="audio_player" preload="auto">
  <source src="<%= asset_path('196107__aiwha__bell.wav') %>" type="audio/wav">
</audio>

<br>
<br>
<div class="disclaimer">
  Warning: Only use this app if you want amazing things to be manifested into your life!
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PointOfAttraction</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>